##########################################################################
# MULTIMNO - LITE
##########################################################################

FROM ubuntu:22.04

# --------- Set tzdata ----------
# Set the timezone
ENV TZ=Europe/Madrid
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install -y tzdata

# --------- INSTALL Python --------
RUN apt update && \
  apt install -y software-properties-common curl

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

# Install pip
RUN curl https://bootstrap.pypa.io/get-pip.py | python

# ---------- INSTALL System Libraries ----------
# Needed for Pyspark
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  openjdk-17-jdk \
  build-essential \
  software-properties-common \
  gdal-bin \
  libgdal-dev \
  python3-dev \
  python3-pip \
  wget

# ---------- PYTHON DEPENDENCIES ----------

# Install requirements
ARG install_dir=/tmp/install

# Upgrade pip to latest version
RUN pip install --upgrade pip

# Standard requirements
COPY resources/requirements/requirements.in ${install_dir}/requirements/requirements.in
RUN pip install -r ${install_dir}/requirements/requirements.in

# Copy the app and configs
COPY multimno /opt/app/multimno
COPY pipe_configs /opt/app/pipe_configs
COPY orchestrator_multimno.py /opt/app/orchestrator_multimno.py

# ----------- CLEANUP -----------
RUN rm -r ${install_dir}
RUN rm -rf /var/lib/apt/lists/*

# ----------- RUNTIME -----------
ENV PYTHONPATH=/opt/app
WORKDIR /opt/app

CMD ["bash"]