version: '3'

services:
  multimno:
    image: multimno:1.0-dev
    build:
      context: ..
      target: multimno-dev
      args:
        - JDK_VERSION=${JDK_VERSION}
        - SPARK_VERSION=${SPARK_VERSION}
        - SCALA_VERSION=${SCALA_VERSION}
        - SEDONA_VERSION=${SEDONA_VERSION}
        - GEOTOOLS_WRAPPER_VERSION=${GEOTOOLS_WRAPPER_VERSION}
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    command: sleep infinity
    volumes:
      - ..:/opt/app
      - ${DATA_DIR}:/opt/data
      - ${SPARK_LOGS_DIR}:/opt/spark/spark-events
    ports:
      - "127.0.0.1:${JL_PORT}:8888"
      - "127.0.0.1:${SUI_PORT}:4040"
      - "127.0.0.1:${SHS_PORT}:18080"
    deploy:
      resources:
        limits:
          cpus: ${CONTAINER_CPU}
          memory: ${CONTAINER_MEM}
