"""
Settings module
"""

APP_NAME = "MultiMNO"

# System exit codes
SUCCESS_EXIT_CODE = 0
ERROR_EXIT_CODE = 1
QUALITY_WARNINGS_EXIT_CODE = 2

# GENERAL CONFIG KEYS
CONFIG_PATHS_KEY = "Paths"
CONFIG_LANDING_PATHS_KEY = f"{CONFIG_PATHS_KEY}.Landing"
CONFIG_BRONZE_PATHS_KEY = f"{CONFIG_PATHS_KEY}.Bronze"
CONFIG_SILVER_PATHS_KEY = f"{CONFIG_PATHS_KEY}.Silver"
CONFIG_GOLD_PATHS_KEY = f"{CONFIG_PATHS_KEY}.Gold"
CONFIG_EXPORTS_PATHS_KEY = f"{CONFIG_PATHS_KEY}.Exports"

SPARK_CONFIG_KEY = "Spark"
LOG_CONFIG_KEY = "Logging"
GENERAL_CONFIG_KEY = "General"
