APP_NAME = "MultiMNO"

# GENERAL CONFIG KEYS 
CONFIG_PATHS_KEY = "Paths"
CONFIG_LANDING_PATHS_KEY = f'{CONFIG_PATHS_KEY}.Landing'
CONFIG_BRONZE_PATHS_KEY = f'{CONFIG_PATHS_KEY}.Bronze'
CONFIG_SILVER_PATHS_KEY = f'{CONFIG_PATHS_KEY}.Silver'
CONFIG_GOLD_PATHS_KEY = f'{CONFIG_PATHS_KEY}.Gold'

SPARK_CONFIG_KEY = "Spark"
LOG_CONFIG_KEY = "Logging"
