#!/bin/bash

# Clear the output of all notebooks
notebooks=$(find . -type f -name "*.ipynb")
if [ -n "$notebooks" ]; then
    echo "$notebooks" | xargs jupyter nbconvert --clear-output --inplace
else
    echo "No Jupyter notebooks found to clear output."
fi


# Format all Python files of KineoDataops
black -l 120 multimno tests/test_code/

# Add only the staged files again
git diff --name-only --cached | xargs git add

exit 0